### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by Nuginu** [leejt/hitsplat-tracker#1]
Very interested, but where do we view or save the data?

**Comment by leejt** [comment]
Right now it's pretty rudimentary - the data gets saved to the client.log file (which you can get to by right-clicking the screenshot button in RuneLite, clicking "Open screenshot folder", and navigating up a level to find the "logs" folder.

**Comment by Nuginu** [comment]
That's perfect, all I needed to know. I just had no idea it was going into the logs lol. Thanks!
